package basashi.erm.model;
//Date: 平成 28/5/24 21:44:01
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

public class ModelLittleGirl extends ModelERMBase
{
	// デフォルトテクスチャ
	private final static ResourceLocation DEFAULT =  new ResourceLocation("erm:textures/entity/littlegirl_default.png");
	//fields
	ModelRenderer bottom;
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer rightArm;
	ModelRenderer rightLeg;
	ModelRenderer leftArm;
	ModelRenderer leftLeg;

	public ModelLittleGirl()
	{
		textureWidth = 96;
		textureHeight = 48;

		bottom = new ModelRenderer(this, 0, 29);
		bottom.addBox(-3.5F, -1F, -3F, 7, 6, 6);
		bottom.setRotationPoint(0F, 15F, 0F);
		bottom.setTextureSize(96, 48);
		bottom.mirror = true;
		setRotation(bottom, 0F, 0F, 0F);
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8);
		head.setRotationPoint(0F, 8F, 0F);
		head.setTextureSize(96, 48);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		body = new ModelRenderer(this, 0, 16);
		body.addBox(-3F, 0F, -2F, 6, 7, 4);
		body.setRotationPoint(0F, 8F, 0F);
		body.setTextureSize(96, 48);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		rightArm = new ModelRenderer(this, 32, 0);
		rightArm.addBox(-2F, -1F, -1F, 2, 8, 2);
		rightArm.setRotationPoint(-3F, 9.5F, 0F);
		rightArm.setTextureSize(96, 48);
		rightArm.mirror = true;
		setRotation(rightArm, 0F, 0F, 0.1570796F);
		rightLeg = new ModelRenderer(this, 20, 16);
		rightLeg.addBox(-2F, 0F, -2F, 3, 9, 4);
		rightLeg.setRotationPoint(-1F, 15F, 0F);
		rightLeg.setTextureSize(96, 48);
		rightLeg.mirror = true;
		setRotation(rightLeg, 0F, 0F, 0F);
		leftArm = new ModelRenderer(this, 40, 0);
		leftArm.addBox(0F, -1F, -1F, 2, 8, 2);
		leftArm.setRotationPoint(3F, 9.5F, 0F);
		leftArm.setTextureSize(96, 48);
		leftArm.mirror = true;
		setRotation(leftArm, 0F, 0F, -0.1570796F);
		leftLeg = new ModelRenderer(this, 34, 16);
		leftLeg.addBox(-1F, 0F, -2F, 3, 9, 4);
		leftLeg.setRotationPoint(1F, 15F, 0F);
		leftLeg.setTextureSize(96, 48);
		leftLeg.mirror = true;
		setRotation(leftLeg, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5,entity);
		head.render(f5);
		body.render(f5);
		rightArm.render(f5);
		rightLeg.render(f5);
		leftArm.render(f5);
		leftLeg.render(f5);
		bottom.render(f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	// テクスチャサイズを更新する
	@Override
	public  void updateTextureSize(int width, int height){
		this.textureHeight = height;
		this.textureWidth = width;
		bottom.setTextureSize(width, height);
		head.setTextureSize(width, height);
		body.setTextureSize(width, height);
		rightArm.setTextureSize(width, height);
		rightLeg.setTextureSize(width, height);
		leftArm.setTextureSize(width, height);
		leftLeg.setTextureSize(width, height);
	}

	/**
	 * デフォルトのテクスチャを返す
	 */
	@Override
	public ResourceLocation getDefaultResource() {
		return DEFAULT;
	}



}
